using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PVerify.Models.PVerify
{
    public enum PracticeTypeCode
    {
        DME = 3,
        Chemotherapy = 8,
        VisionOptometry = 9,
        MentalHealth = 21,
        PhysicalTherapy = 12,
        PrimaryCare = 17,
        Specialist_Office = 18,
        Surgical_Office = 22,
        UrgentCare = 23,
        DiagnosticLab = 24,
        Specialist_Office_Surgical_Office_Diagnostic_Lab = 27,
        ASC_Facility = 28,
        Chiropractic = 30,
        MRI_CAT_Scan = 31,
        X_Ray = 32,
        SpeechTherapy = 33,
        OccupationalTherapy = 34,
        ASC_Specialist_Office_VisionOptometry = 35,
        Specialist_Office_Chemotherapy = 36,
        Physical_Therapy_Chiropractic = 37,
        Physical_Therapy_DME = 38,
        Physical_Therapy_Occupational_Therapy_DME = 39,
        Physical_Therapy_Occupational_Therapy_Speech_Therapy = 40,
        Specialist_Office_VisionOptometry = 41,
        Specialist_Office_DME = 42,
        Specialist_Office__Surgical_Office_ = 43,
        Specialist_Office__ASC_Facility = 44,
        Physical_Therapy_XRay = 45,
        XRay_MRI_CAT_Scan = 46,
        Speech_Therapy_Occupational_Therapy = 53,
        Emergency_Services = 54,
        Routine_Physical = 55,
        Podiatry_Office = 56,
        Professional_Outpatient_Physician = 57,
        Anesthesia = 58,
        Substance_Abuse = 59,
        Substance_Abuse_Facility_InPatient = 60,
        Substance_Abuse_Facility_OutPatient = 61,
        Telemedicine = 62,
        Flu_Vaccination = 63,
        Mental_Health_Sub_Abuse_Professional = 64,
        Mental_Health_Sub_Abuse_In_OutFacility = 65,
        Sub_Abuse_In_OutFacility = 66,
        Mental_Health_SubAbuse_In_NetFacility = 67,
        Specialist_Office_ASC_Professional_OutPatient = 68,
        ASC_Facility_Professional_OutPatient = 69,
        General_Office_Benefits_30 = 70,
        Podiatry_XRay_DME = 71,
        Podiatry_DME = 72,
        Hospital_InPatient = 73,
        Emergency_Services_Hospital_InPatient = 74,
        Speech_Therapy_Occupational_Therapy_MentalHealth = 75,
        DME_Diagnostic_Lab = 76,
        Pharmacy = 77,
        Specialist_Office__Pharmacy = 78,
        Physical_Therapy_Occupational_Therapy_Mental_Health = 79,
        Specialist_Office_DME_ASC_Facility = 80,
        Specialist_Office_DME_Surgical_Office_ = 81,
        Specialist_Office_DME_Hospital_OutPatient = 82,
        Hospital_OutPatient = 83,
        Physical_Therapy_Occupational_Therapy = 84,
        Specialist_Office_Surgery_Office__DME = 85,
        SpecialistOffice_DME_X_Ray = 87,
        SpecialistOffice_Physical_Therapy = 88,
        Telemedicine_Primary_Care = 89,
        Telemedicine_Specialist_Services = 90,
        Telemedicine_Urgent_Care = 91,
        Telemedicine_Physical_Therapy = 92,
        Telemedicine_Mental_Health = 93,
        Psychotherapy = 94,
        Telemedicine_Primary_Telemedicine_Specialist = 95,
        Telemedicine_Primary_Telemedicine_Specialist_Telemedicine_Urgent_care = 96,
        Specialist_Office_Psychotherapy = 97,
        Hospital_Outpatient_Surgical_Office_Specialist_Office = 100,
        SNF_AG_ = 101,
        SNF_Room_and_Board_AH = 102,
        SNF_SNF_Room_and_Board = 103,
        Specialist_Office__Mental_Health = 104,
        Specialist_office__Primary_Care_Chiropractic = 105,
        Occupational_Therapy_DME = 106,
        Professional_Physician_Visit_Inpatient_99 = 107,
        Home_Health_Care_42 = 108,
        Hospice_45 = 109,
        Home_Health_42_Hospice_45 = 110,
        Mental_Health_Telemedicine__Mental_Health__MH = 111
    }
}
